spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: ${ES_IP_PORT}
      properties:
        path:
          logs: ./elasticsearch/log #elasticsearch日志存储目录
          data: ./elasticsearch/data #elasticsearch数据存储目录
  datasource:
    primary:
      url: jdbc:mysql://${MYSQL_URL:47.92.159.54:3306}/${COMPANY:company}?autoReconnect=true&useUnicode=true
      username: root
      password: ${MYSQL_PASS}
    secondary:
      url: jdbc:mysql://${MYSQL_URL:47.92.159.54:3306}/${EC_SERVER:ec_server}?autoReconnect=true&useUnicode=true
      username: root
      password: ${MYSQL_PASS}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: 10000
  kafka:
    bootstrap-servers: ${KAFKA}:9092
open:
  eureka: true
  