spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 47.92.107.76:10022
      properties:
        path:
          logs: ./elasticsearch/log #elasticsearch日志存储目录
          data: ./elasticsearch/data #elasticsearch数据存储目录
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy #命名策略，加分隔线"_"
  profiles:
    active: ${ENV:dev}
ecServer:
  ecBaseUri: https://open.workec.com/
logging:
  file: ./logback.log
logstash:
  ip: ${logstashIp:localhost}
  port: ${logstashPort:4560}
