spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/company?autoReconnect=true&useUnicode=true&characterEncoding=utf8
      username: root
      password: root
    secondary:
      url: jdbc:mysql://localhost:3306/ec_server?autoReconnect=true&useUnicode=true&characterEncoding=utf8
      username: root
      password: root
