spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: ${ES_IP_PORT}
      properties:
        path:
          logs: ./elasticsearch/log #elasticsearch日志存储目录
          data: ./elasticsearch/data #elasticsearch数据存储目录
  datasource:
    primary:
      url: jdbc:mysql://${MYSQL_URL:172.26.249.246:3306}/${COMPANY:company}?autoReconnect=true&useUnicode=true
      username: md
      password: ${MYSQL_PASS}
    secondary:
      url: jdbc:mysql://${MYSQL_URL:172.26.249.246:3306}/${EC_SERVER:ec_server}?autoReconnect=true&useUnicode=true
      username: md
      password: ${MYSQL_PASS}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
open:
  eureka: true
  